import Head from 'next/head';
import Image from 'next/image';
import hero from "../public/about-us_hero-image.png"

const About = () => {
    return (
        <div>
            <Head>
                <title>Growtech-About Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="px-4 sm:px-5 md:px-6 lg:px-8">
                <h2 className="text-3xl text-normal text-center md:text-4xl lg:text-5xl">About Us</h2>
                <Image src={hero} className="rounded-3xl" />
                <p className="">Growtech Farms was established to elevate the Agriculture sector by using modern technologies.
                     Our Philippine-Israeli team has more than 20 years combined experience in Agriculture and Business Development</p>
            </div>
        </div>
    )
}

export default About
