
import Head from 'next/head'
import AboutTop from '../components/aboutUs/aboutUSTop'
import AboutMid from '../components/aboutUs/aboutUsMid'
import AboutBot from '../components/aboutUs/aboutUsBot'


const About = () => {
    return (
        <div>
            <Head>
                <title>Growtech-About Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

                <AboutTop/>
                <AboutMid/>  
                <AboutBot/> 
        </div>
    )
}

export default About
