import Head from 'next/head'



const About = () => {
    return (
        <div>
            <Head>
                <title>Growtech-About Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="text-center">
                About page
            </div>
        </div>
    )
}

export default About
