import Head from 'next/head'


const Blogs = () => {
    return (
        <div>
            <Head>
                <title>Growtech-Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex justify-center py-10">
                    <span className="inline-block h-1 w-20 rounded bg-green-500 mt-6 mb-4 md:w-40"></span>
                    <h1 className="pt-3 text-3xl font-bold mx-4 md:text-6xl md:pt-0">OUR BLOGS</h1>
                    <span className="inline-block h-1 w-20 rounded bg-green-500 mt-6 mb-4 md:w-40"></span>
                </div>
        </div>
    )
}

export default Blogs
