import Head from 'next/head'


const Blogs = () => {
    return (
        <div>
            <Head>
                <title>Growtech-Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className="text-gray-400 text-center">
                Blogs
            </div>
        </div>
    )
}

export default Blogs
