import React from 'react'
import Head from 'next/head'
import ContactMap from '../components/contactUs/contactMap'
import ContactInquiry from '../components/contactUs/contactInquiry'

const Contact = () => {
    return (
        <div>
            <Head>
                <title>Growtech-Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="text-center text-gray-600">
            <div className="flex justify-center py-10">
                    <span className="inline-block h-1 w-20 rounded bg-green-500 mt-6 mb-4 md:w-40"></span>
                    <h1 className="pt-3 text-3xl font-bold mx-4 md:text-6xl md:pt-0">CONTACT US</h1>
                    <span className="inline-block h-1 w-20 rounded bg-green-500 mt-6 mb-4 md:w-40"></span>
                </div>
            <section className="text-gray-600 body-font relative">
                <div className="container px-5 mb-10 py-2 md:py-10 mx-auto flex sm:flex-nowrap flex-wrap">
                 <ContactMap/>
                <ContactInquiry/>
                </div>
                </section>


                
            </div>
        </div>
    )
}

export default Contact
