import React from 'react'
import Head from 'next/head'

const Contact = () => {
    return (
        <div>
            <Head>
                <title>Growtech-Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="text-center text-gray-600">
                Contact
            </div>
        </div>
    )
}

export default Contact
