import React from 'react'
import Head from 'next/head'


function ourFeatures() {
    return (
        <div>
            <Head>
                <title>Growtech-Our Features</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                OurFeature
            </div>
        </div>
    )
}

export default ourFeatures
