import React from "react";
import Head from "next/head";
import Image from "next/image";
import indoor from "../public/indoor.jpg";

function ourFeatures() {
    return (
        <div>
            <Head>
                <title>Growtech-Our Features</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Head>
                    <title>Our Services</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <section class="text-gray-600 body-font">
                    <div class="container px-5 py-24 mx-auto">
                        <div class="flex flex-col text-center w-full mb-20">
                            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
                                Your Lettuces' happy little home
                            </h1>
                        </div>
                        <div class="flex flex-wrap">
                            <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                                <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                                    Indoor Farming
                                </h2>
                                <Image src={indoor} height="300" width="400" />
                                <a class="text-indigo-500 inline-flex items-center">
                                    Learn More
                                    <svg
                                        fill="none"
                                        stroke="currentColor"
                                        stroke-linecap="round"
                                        stroke-linejoin="round"
                                        stroke-width="2"
                                        class="w-4 h-4 ml-2"
                                        viewBox="0 0 24 24">
                                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                        <div class="container px-5 py-24 mx-auto">
                            <div class="flex flex-wrap w-full mb-20">
                                <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
                                    <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
                                        Pitchfork Kickstarter Taxidermy
                                    </h1>
                                    <div class="h-1 w-20 bg-indigo-500 rounded"></div>
                                </div>
                                <p class="lg:w-1/2 w-full leading-relaxed text-gray-500">
                                    Whatever cardigan tote bag tumblr hexagon
                                    brooklyn asymmetrical gentrify, subway tile
                                    poke farm-to-table. Franzen you probably
                                    haven't heard of them man bun deep jianbing
                                    selfies heirloom prism food truck ugh squid
                                    celiac humblebrag.
                                </p>
                            </div>
                            <div class="flex flex-wrap -m-4">
                                <div class="xl:w-1/4 md:w-1/2 p-4">
                                    <div class="bg-gray-100 p-6 rounded-lg">
                                        <img class="h-40 rounded w-full object-cover object-center mb-6" src="https://dummyimage.com/720x400" alt="content"></img>
                                        <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">SUBTITLE</h3>
                                        <h2 class="text-lg text-gray-900 font-medium title-font mb-4">Chichen Itza</h2>
                                        <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
                                    </div>
                                </div>
                                <div class="xl:w-1/4 md:w-1/2 p-4">
                                    <div class="bg-gray-100 p-6 rounded-lg">
                                        <img class="h-40 rounded w-full object-cover object-center mb-6" src="https://dummyimage.com/722x402" alt="content" />
                                        <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">SUBTITLE</h3>
                                        <h2 class="text-lg text-gray-900 font-medium title-font mb-4">Great Pyramid of Giza</h2>
                                        <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
                                    </div>
                                </div>
                                <p class="lg:w-1/2 w-full leading-relaxed text-gray-500">
                                    Whatever cardigan tote bag tumblr hexagon
                                    brooklyn asymmetrical gentrify, subway tile
                                    poke farm-to-table. Franzen you probably
                                    haven't heard of them man bun deep jianbing
                                    selfies heirloom prism food truck ugh squid
                                    celiac humblebrag.
                                </p>
                                {/* <div class="xl:w-1/4 md:w-1/2 p-4">
                                    <div class="bg-gray-100 p-6 rounded-lg">
                                    <img class="h-40 rounded w-full object-cover object-center mb-6" src="https://dummyimage.com/723x403" alt="content">
                                    <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">SUBTITLE</h3>
                                    <h2 class="text-lg text-gray-900 font-medium title-font mb-4">San Francisco</h2>
                                    <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
                                    </div>
                                </div>
                                </div> */}
                            </div>
                        </div>
                        <button class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                            Talk to us
                        </button>
                    </div>
                </section>
            </div>
        </div>
    );
}

export default ourFeatures;
