import React from "react";
import Head from "next/head";
import Image from "next/image";
import indoor from "../public/indoor.jpg";

function ourFeatures() {
    return (
        <div>
            <Head>
                <title>Growtech-Our Features</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Head>
                    <title>Our Services</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <section className="text-gray-600 body-font">
                <div className="flex justify-center py-10">
                    <span className="inline-block h-1 w-20 rounded bg-green-500 mt-6 mb-4 md:w-40"></span>
                    <h1 className="text-3xl text-center font-bold mx-6 md:text-6xl md:pt-0">MAIN FEATURES</h1>
                    <span className="inline-block h-1 w-20 rounded bg-green-500 mt-6 mb-4 md:w-40"></span>
                </div>
                    <div className="container px-5 py-24 mx-auto">
                        <div className="flex flex-col text-center w-full mb-20">
                            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
                                Your Lettuces&apos; happy little home
                            </h1>
                        </div>
                        <div className="flex flex-wrap">
                            <div className="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                                <h2 className="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                                    Indoor Farming
                                </h2>
                                <Image src={indoor} height={300} width={400} alt="image"/>
                                <a className="text-indigo-500 inline-flex items-center">
                                    Learn More
                                    <svg
                                        fill="none"
                                        stroke="currentColor"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth="2"
                                        className="w-4 h-4 ml-2"
                                        viewBox="0 0 24 24">
                                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                                    </svg>
                                </a>
                            </div>
                        </div>
                        <div className="container px-5 py-24 mx-auto">
                            <div className="flex flex-wrap w-full mb-20">
                                <div className="lg:w-1/2 w-full mb-6 lg:mb-0">
                                    <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
                                        Pitchfork Kickstarter Taxidermy
                                    </h1>
                                    <div className="h-1 w-20 bg-indigo-500 rounded"></div>
                                </div>
                                <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">
                                    Whatever cardigan tote bag tumblr hexagon
                                    brooklyn asymmetrical gentrify, subway tile
                                    poke farm-to-table. Franzen you probably
                                    haven&apos;t heard of them man bun deep jianbing
                                    selfies heirloom prism food truck ugh squid
                                    celiac humblebrag.
                                </p>
                            </div>
                            <div className="flex flex-wrap -m-4">
                                <div className="xl:w-1/4 md:w-1/2 p-4">
                                    <div className="bg-gray-100 p-6 rounded-lg">
                                    <Image className="h-40 rounded w-full object-cover object-center mb-6" 
                                        src={'https://dummyimage.com/722x402'} 
                                        width={722}
                                        height={402}
                                        alt="content" 
                                        />
                                        <h3 className="tracking-widest text-indigo-500 text-xs font-medium title-font">SUBTITLE</h3>
                                        <h2 className="text-lg text-gray-900 font-medium title-font mb-4">Chichen Itza</h2>
                                        <p className="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
                                    </div>
                                </div>
                                <div className="xl:w-1/4 md:w-1/2 p-4">
                                    <div className="bg-gray-100 p-6 rounded-lg">
                                        <Image className="h-40 rounded w-full object-cover object-center mb-6" 
                                        src={'https://dummyimage.com/722x402'} 
                                        width={722}
                                        height={402}
                                        alt="content" 
                                        />
                                        <h3 className="tracking-widest text-indigo-500 text-xs font-medium title-font">SUBTITLE</h3>
                                        <h2 className="text-lg text-gray-900 font-medium title-font mb-4">Great Pyramid of Giza</h2>
                                        <p className="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
                                    </div>
                                </div>
                                <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">
                                    Whatever cardigan tote bag tumblr hexagon
                                    brooklyn asymmetrical gentrify, subway tile
                                    poke farm-to-table. Franzen you probably
                                    haven&apos;t heard of them man bun deep jianbing
                                    selfies heirloom prism food truck ugh squid
                                    celiac humblebrag.
                                </p>
                                {/* <div className="xl:w-1/4 md:w-1/2 p-4">
                                    <div className="bg-gray-100 p-6 rounded-lg">
                                    <img className="h-40 rounded w-full object-cover object-center mb-6" src="https://dummyimage.com/723x403" alt="content">
                                    <h3 className="tracking-widest text-indigo-500 text-xs font-medium title-font">SUBTITLE</h3>
                                    <h2 className="text-lg text-gray-900 font-medium title-font mb-4">San Francisco</h2>
                                    <p className="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
                                    </div>
                                </div>
                                </div> */}
                            </div>
                        </div>
                        <button className="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                            Talk to us
                        </button>
                    </div>
                </section>
            </div>
        </div>
    );
}

export default ourFeatures;
