import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/homepage/hero'
import Products from '../components/homepage/products'
import Cart from '../components/homepage/cartcheck'
import Productfeature from '../components/homepage/pruductfeature'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Growtech-Shop-Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Cart />
      <Productfeature />
      <Products />
    </div>
  )
}
