import Head from "next/head";
import Image from 'next/image';
import indoor from '../public/indoor.jpg';

const Services = () => {
    return (
        <div>
            <Head>
                <title>Our Services</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section class="text-gray-600 body-font">
                <div class="container px-5 py-24 mx-auto">
                    <div class="flex flex-col text-center w-full mb-20">                     
                        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
                            Our Services
                        </h1>   
                        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                            From sending you planting supplies, and home
                            equipment to large-scale farm building consultancy,
                            we can help!
                        </p>
                    </div>
                    <div class="flex flex-wrap">
                        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                            <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                                Indoor Farming
                            </h2>
                            <Image src={indoor} height="300" width="400" />
                            <p class="leading-relaxed text-base mb-4">
                                Fingerstache flexitarian street art 8-bit
                                waistcoat. Distillery hexagon disrupt edison
                                bulbche.
                            </p>
                            <a class="text-indigo-500 inline-flex items-center">
                                Learn More
                                <svg
                                    fill="none"
                                    stroke="currentColor"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    class="w-4 h-4 ml-2"
                                    viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                            <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                                Indoor Farming
                            </h2>
                            <Image src={indoor} height="300" width="400" />
                            <p class="leading-relaxed text-base mb-4">
                                Fingerstache flexitarian street art 8-bit
                                waistcoat. Distillery hexagon disrupt edison
                                bulbche.
                            </p>
                            <a class="text-indigo-500 inline-flex items-center">
                                Learn More
                                <svg
                                    fill="none"
                                    stroke="currentColor"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    class="w-4 h-4 ml-2"
                                    viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                            <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                                Indoor Farming
                            </h2>
                            <Image src={indoor} height="300" width="400" />
                            <p class="leading-relaxed text-base mb-4">
                                Fingerstache flexitarian street art 8-bit
                                waistcoat. Distillery hexagon disrupt edison
                                bulbche.
                            </p>
                            <a class="text-indigo-500 inline-flex items-center">
                                Learn More
                                <svg
                                    fill="none"
                                    stroke="currentColor"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    class="w-4 h-4 ml-2"
                                    viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                            <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                                Indoor Farming
                            </h2>
                            <Image src={indoor} height="300" width="400" />
                            <p class="leading-relaxed text-base mb-4">
                                Fingerstache flexitarian street art 8-bit
                                waistcoat. Distillery hexagon disrupt edison
                                bulbche.
                            </p>
                            <a class="text-indigo-500 inline-flex items-center">
                                Learn More
                                <svg
                                    fill="none"
                                    stroke="currentColor"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    class="w-4 h-4 ml-2"
                                    viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                    <button class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                        Talk to us
                    </button>
                </div>
            </section>
        </div>
    );
};

export default Services;
